version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: resolver
      POSTGRES_PASSWORD: resolver
      POSTGRES_DB: resolver
    networks:
        - resolver-network
  resolver:
    container_name: resolver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    env_file:
      - ./build/.env
    networks:
        - resolver-network

networks:
  resolver-network:
    driver: bridge